Repository Soluto/monitored, pull requests merged in 2022-07, with the labels that each got.

#42 contribution file alignment
  .github/CONTRIBUTING.md
Labels: small

#46 Report result was found or not
  README.md
  __tests__/PrometheusPlugin.spec.ts
  __tests__/StatsdPlugin.spec.ts
  __tests__/__mocks__/plugins/StatsdPlugin.ts
  __tests__/monitor.spec.ts
  package.json
  src/Monitor.ts
  src/plugins/PluginsWrapper.ts
  src/plugins/PrometheusPlugin.ts
  src/plugins/StatsdPlugin.ts
  src/plugins/types.ts
  src/types.ts
Labels: large

#44 Support typed increment
  example/run.ts
  src/plugins/PluginsWrapper.ts
  src/plugins/types.ts
Labels: enhancement, small
